version: "2"
services:
  flask:
    image: webapp-flask
    build:
      context: ./app
      dockerfile: Dockerfile
    links:
      - db
    volumes:
      - "./:/app"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  nginx:
    image: webapp-nginx
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 56734:80
    depends_on:
      - flask