version: '3'
services:
  flask:
    image: webapp-flask-w
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - "./:/app"

  nginx:
    image: webapp-nginx-w
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 56734:80
    depends_on:
      - flask

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro